
//THIS IS CONST TYPE OF HOME PAGE REDUCER AND ACTION.
export const GET_HOMEDATA_DISPATCH = 'GET_HOMEDATA_DISPATCH';
export const GET_HOMEDATA_SUCCESS = 'GET_HOMEDATA_SUCCESS';
export const GET_HOMEDATA_FAIL = 'GET_HOMEDATA_FAIL';
export const DELETE_HOMEDATA_FAIL = 'DELETE_HOMEDATA_FAIL';
export const DELETE_HOMEDATA_SUCCESS = 'DELETE_HOMEDATA_FAIL';

//THIS IS CONST TYPE OF UNIVERSITIES PAGE REDUCER AND ACTION. 


export const BASE_URL = 'https://jsonplaceholder.typicode.com/posts';
