
//THIS IS CONST TYPE OF HOME PAGE REDUCER AND ACTION.
export const GET_HOMEDATA_DISPATCH = 'GET_HOMEDATA_DISPATCH';
export const GET_HOMEDATA_SUCCESS = 'GET_HOMEDATA_SUCCESS';
export const GET_HOMEDATA_FAIL = 'GET_HOMEDATA_FAIL';

//THIS IS CONST TYPE OF UNIVERSITIES PAGE REDUCER AND ACTION.
export const GET_UNIVERSITIES_DATA_DISPATCH = 'GET_UNIVERSITIES_DATA_DISPATCH';
export const GET_UNIVERSITIES_DATA_SUCCESS = 'GET_UNIVERSITIES_DATA_SUCCESS';
export const GET_UNIVERSITIES_DATA_FAIL = 'GET_UNIVERSITIES_DATA_FAIL';
export const GET_UNIVERSITIES_CITIES = 'GET_UNIVERSITIES_CITIES';
export const GET_UNIVERSITIES_CITIES_FAIL = 'GET_UNIVERSITIES_CITIES_FAIL';


//THIS IS CONST TYPE OF LOOKUP PAGE REDUCER AND ACTION.
export const GET_POSTALLOOK_DISPATCH = 'GET_POSTALLOOK_DISPATCH';
export const GET_POSTALLOOK_SUCCESS = 'GET_POSTALLOOK_SUCCESS';
export const GET_POSTALLOOK_FAIL = 'GET_POSTALLOOK_FAIL';


export const BASE_URL = 'https://jsonplaceholder.typicode.com/posts';
export const UNIVERSITY_URL = 'http://universities.hipolabs.com/';
export const COUNTRY_URL = "https://restcountries.com/v3.1/all";
export const SEARCH_URL = "https://api.zippopotam.us/us";
